modLoader   = "javafml"
loaderVersion = "[47,)"
license     = "MIT"
issueTrackerURL = "https://github.com/jmoiron/gcyr-extras/issues"
logoFile    = "icon.png"

[[mods]]
modId       = "gcyrextras"
version     = "${file.jarVersion}"
displayName = "GCYR Extras"
description = '''Extra rocket tiers for Gregicality Rocketry'''

[[dependencies.gcyrextras]]
modId        = "forge"
mandatory    = true
versionRange = "[47,)"
ordering     = "NONE"
side         = "BOTH"

[[dependencies.gcyrextras]]
modId        = "minecraft"
mandatory    = true
versionRange = "[1.20.1,1.21)"
ordering     = "NONE"
side         = "BOTH"

[[dependencies.gcyrextras]]
modId        = "gcyr"
mandatory    = true
versionRange = "[0.2.8,)"
ordering     = "AFTER"
side         = "BOTH"

